"""add grammar_audits and grammar_issues

Revision ID: 0b176b7f1127
Revises: 2d78cb0f709a
Create Date: 2025-09-14 09:32:04.872907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0b176b7f1127'
down_revision: Union[str, Sequence[str], None] = '2d78cb0f709a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grammar_audits',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('revision_id', sa.BigInteger(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('issue_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['revision_id'], ['note_revisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grammar_audits_id'), 'grammar_audits', ['id'], unique=False)
    op.create_index(op.f('ix_grammar_audits_revision_id'), 'grammar_audits', ['revision_id'], unique=False)
    op.create_table('grammar_issues',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('audit_id', sa.BigInteger(), nullable=False),
    sa.Column('revision_id', sa.BigInteger(), nullable=False),
    sa.Column('start', sa.Integer(), nullable=False),
    sa.Column('length', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('rule_id', sa.String(length=128), nullable=True),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('original', sa.Text(), nullable=False),
    sa.Column('replacements', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_applied', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['grammar_audits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['revision_id'], ['note_revisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grammar_issues_audit_id'), 'grammar_issues', ['audit_id'], unique=False)
    op.create_index(op.f('ix_grammar_issues_id'), 'grammar_issues', ['id'], unique=False)
    op.create_index(op.f('ix_grammar_issues_revision_id'), 'grammar_issues', ['revision_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_grammar_issues_revision_id'), table_name='grammar_issues')
    op.drop_index(op.f('ix_grammar_issues_id'), table_name='grammar_issues')
    op.drop_index(op.f('ix_grammar_issues_audit_id'), table_name='grammar_issues')
    op.drop_table('grammar_issues')
    op.drop_index(op.f('ix_grammar_audits_revision_id'), table_name='grammar_audits')
    op.drop_index(op.f('ix_grammar_audits_id'), table_name='grammar_audits')
    op.drop_table('grammar_audits')
    # ### end Alembic commands ###
