"""tags: title->CITEXT; add (user_id,title) partial unique index

Revision ID: 1c157df8294a
Revises: 4ccf66c8f0c3
Create Date: 2025-08-27 16:13:59.589992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c157df8294a'
down_revision: Union[str, Sequence[str], None] = '4ccf66c8f0c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('tags', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('tags', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('tags', 'title',
               existing_type=sa.VARCHAR(length=64),
               type_=postgresql.CITEXT(),
               existing_nullable=False)
    op.drop_constraint(op.f('uq_tags_user_title'), 'tags', type_='unique')
    op.create_index('ix_tags_user_active', 'tags', ['user_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('uq_tags_user_title_active', 'tags', ['user_id', 'title'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_tags_user_title_active', table_name='tags', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_tags_user_active', table_name='tags', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_unique_constraint(op.f('uq_tags_user_title'), 'tags', ['user_id', 'title'], postgresql_nulls_not_distinct=False)
    op.alter_column('tags', 'title',
               existing_type=postgresql.CITEXT(),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    op.drop_column('tags', 'deleted_at')
    op.drop_column('tags', 'updated_at')
    op.drop_column('tags', 'is_active')
    # ### end Alembic commands ###
