"""Add is_public and folder_id to note_revisions

Revision ID: 3e2f5c88b596
Revises: c0666d6d7dfb
Create Date: 2025-09-12 23:15:09.333228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e2f5c88b596'
down_revision: Union[str, Sequence[str], None] = 'c0666d6d7dfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note_revisions', sa.Column('is_public', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('note_revisions', sa.Column('folder_id', sa.BigInteger(), nullable=True))
    op.create_index('ix_note_revisions_folder', 'note_revisions', ['folder_id'], unique=False)
    op.create_index('ix_note_revisions_public', 'note_revisions', ['is_public'], unique=False)
    op.create_foreign_key(None, 'note_revisions', 'folders', ['folder_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'note_revisions', type_='foreignkey')
    op.drop_index('ix_note_revisions_public', table_name='note_revisions')
    op.drop_index('ix_note_revisions_folder', table_name='note_revisions')
    op.drop_column('note_revisions', 'folder_id')
    op.drop_column('note_revisions', 'is_public')
    # ### end Alembic commands ###
