"""folders: title->CITEXT; add (user_id,parent_id,title) partial unique index

Revision ID: 4ccf66c8f0c3
Revises: cdc8282e94f9
Create Date: 2025-08-27 15:14:48.582425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4ccf66c8f0c3'
down_revision: Union[str, Sequence[str], None] = 'cdc8282e94f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('folders', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('folders', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('folders', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('folders', 'title',
               existing_type=sa.VARCHAR(length=120),
               type_=postgresql.CITEXT(),
               existing_nullable=False)
    op.create_index('ix_folders_user_parent_active', 'folders', ['user_id', 'parent_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('uq_folders_user_parent_title_active', 'folders', ['user_id', 'parent_id', 'title'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_folders_user_parent_title_active', table_name='folders', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_folders_user_parent_active', table_name='folders', postgresql_where=sa.text('deleted_at IS NULL'))
    op.alter_column('folders', 'title',
               existing_type=postgresql.CITEXT(),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
    op.drop_column('folders', 'deleted_at')
    op.drop_column('folders', 'updated_at')
    op.drop_column('folders', 'is_active')
    # ### end Alembic commands ###
