"""note_revisions: title->CITEXT; add (user_id,title) partial unique index

Revision ID: 7def3fbf6bab
Revises: 1c157df8294a
Create Date: 2025-08-28 11:59:09.327677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7def3fbf6bab'
down_revision: Union[str, Sequence[str], None] = '1c157df8294a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note_revisions', sa.Column('user_id', sa.BigInteger(), nullable=True))
    op.add_column('note_revisions', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('note_revisions', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('note_revisions', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('note_revisions', 'title',
               existing_type=sa.VARCHAR(length=200),
               type_=postgresql.CITEXT(),
               existing_nullable=False)
    op.drop_index(op.f('note_revisions_note_idx'), table_name='note_revisions')
    op.create_index('ix_note_revisions_note', 'note_revisions', ['note_id'], unique=False)
    op.create_index('ix_note_revisions_note_active', 'note_revisions', ['note_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_constraint(op.f('note_revisions_created_by_fkey'), 'note_revisions', type_='foreignkey')
    op.create_foreign_key(None, 'note_revisions', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_column('note_revisions', 'created_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note_revisions', sa.Column('created_by', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'note_revisions', type_='foreignkey')
    op.create_foreign_key(op.f('note_revisions_created_by_fkey'), 'note_revisions', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.drop_index('ix_note_revisions_note_active', table_name='note_revisions', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_note_revisions_note', table_name='note_revisions')
    op.create_index(op.f('note_revisions_note_idx'), 'note_revisions', ['note_id'], unique=False)
    op.alter_column('note_revisions', 'title',
               existing_type=postgresql.CITEXT(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.drop_column('note_revisions', 'deleted_at')
    op.drop_column('note_revisions', 'updated_at')
    op.drop_column('note_revisions', 'is_active')
    op.drop_column('note_revisions', 'user_id')
    # ### end Alembic commands ###
