"""Add updated_at and deleted_at to issues table

Revision ID: c0666d6d7dfb
Revises: fix_notes_version_citext
Create Date: 2025-09-06 00:55:00.973684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0666d6d7dfb'
down_revision: Union[str, Sequence[str], None] = 'fix_notes_version_citext'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('issues', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('notes', 'version',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.drop_index(op.f('notes_folder_idx'), table_name='notes')
    op.drop_index(op.f('notes_user_idx'), table_name='notes')
    op.create_index('ix_notes_folder', 'notes', ['folder_id'], unique=False)
    op.create_index('ix_notes_user', 'notes', ['user_id'], unique=False)
    op.create_unique_constraint('uq_notes_user_folder_title_active', 'notes', ['user_id', 'folder_id', 'title'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_notes_user_folder_title_active', 'notes', type_='unique')
    op.drop_index('ix_notes_user', table_name='notes')
    op.drop_index('ix_notes_folder', table_name='notes')
    op.create_index(op.f('notes_user_idx'), 'notes', ['user_id'], unique=False)
    op.create_index(op.f('notes_folder_idx'), 'notes', ['folder_id'], unique=False)
    op.alter_column('notes', 'version',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.drop_column('issues', 'deleted_at')
    op.drop_column('issues', 'updated_at')
    # ### end Alembic commands ###
