"""Fixed notes and tags relationships

Revision ID: c275a1c93262
Revises: 3e2f5c88b596
Create Date: 2025-09-13 13:32:06.226192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c275a1c93262'
down_revision: Union[str, Sequence[str], None] = '3e2f5c88b596'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
