"""Add tags to note_revisions table

Revision ID: c98ea2bca9d5
Revises: c275a1c93262
Create Date: 2025-09-13 15:09:38.402664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c98ea2bca9d5'
down_revision: Union[str, Sequence[str], None] = 'c275a1c93262'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note_revision_tags',
    sa.Column('revision_id', sa.BigInteger(), nullable=False),
    sa.Column('tag_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['revision_id'], ['note_revisions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('revision_id', 'tag_id')
    )
    op.create_index('ix_note_revision_tags_revision', 'note_revision_tags', ['revision_id'], unique=False)
    op.create_index('ix_note_revision_tags_tag', 'note_revision_tags', ['tag_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_note_revision_tags_tag', table_name='note_revision_tags')
    op.drop_index('ix_note_revision_tags_revision', table_name='note_revision_tags')
    op.drop_table('note_revision_tags')
    # ### end Alembic commands ###
